steps:
  - name: "gcr.io/cloud-builders/git"
    args: [ "clone", "https://github.com/mbabiak39/roimb-devopsuser10-dev.git", "." ]

  - name: "hashicorp/terraform:light"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform/
        terraform init \
          -input=false \

  - name: "hashicorp/terraform:light"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform/
        terraform plan \
          -input=false \
          -var-file=input_vars.tfvars \
          -out=tfplan

  - name: "hashicorp/terraform:light"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform/
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan

options:
  logging: CLOUD_LOGGING_ONLY